// <auto-generated />
namespace HotelGestion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UniDBSchema13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UniDBSchema13));
        
        string IMigrationMetadata.Id
        {
            get { return "202109302139485_UniDBSchema13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
